# running version development
FROM node:20-alpine

# directory container
WORKDIR /app

# copy package json ke container diatas
COPY package* .

RUN npm i

# ini semua file bakal masuk ke container
COPY . .

# akan running project setelah semua yg diatas ter setup
CMD ["npm", "run", "dev"]